local keybindings = {
	nvim_tree_toggle = '<leader>e',
	telescope_find_files = '<leader>ff',
	telescope_live_grep = '<leader>fg',
	replace_in_files = '<leader>fr',
	dap_continue = '<F5>',
	dap_step_over = '<F6>',
	dap_step_into = '<F7>',
	dap_step_out = '<F8>',
	dap_terminate = '<F10>',
	dap_toggle_breakpoint = '<leader>b',
	dap_clear_all_breakpoints = '<leader>cb',
	lsp_cmp_select_prev = '<C-p>',
	lsp_cmp_select_next = '<C-n>',
	lsp_cmp_complete = '<C-Space>',
	lsp_cmp_confirm = '<CR>',
	lsp_hover = 'K',
	lsp_jump_to_def = 'gd',
	lsp_jump_to_impl = 'gi',
	lsp_list_xrefs = 'lx',
	lsp_rename_symbol = 'rs',
	navigate_jump_back = '[',
	navigate_jump_forward = ']',
	buffer_list_add = '<leader>a',
	buffer_list_toggle = '<leader>o',
	close_buffer = '<leader>x',
	close_window = '<leader>c',
	switch_buffer_next = '<TAB>',
	switch_buffer_prev = '<S-TAB>',
	split_vertically = '<leader>|',
	split_horizontally = '<leader>-',
	switch_window_left = '<leader>h',
	switch_window_below = '<leader>j',
	switch_window_above = '<leader>k',
	switch_window_right = '<leader>l',
	toggle_undo_tree = '<leader>u',
	toggle_git_manager = '<leader>gs',
	uber_paste = '<leader>p',
	toggle_darkmode = '<leader>dm',
	toggle_gitblame = '<leader>gb',
}

return keybindings

